/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ButtonGroup;

/**
 *
 * @author butch
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        make = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        plate = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        service1 = new javax.swing.JRadioButton();
        service2 = new javax.swing.JRadioButton();
        service3 = new javax.swing.JRadioButton();
        service4 = new javax.swing.JRadioButton();
        service5 = new javax.swing.JRadioButton();
        service6 = new javax.swing.JRadioButton();
        service7 = new javax.swing.JCheckBox();
        home = new javax.swing.JButton();
        cost1 = new javax.swing.JLabel();
        cost2 = new javax.swing.JLabel();
        cost3 = new javax.swing.JLabel();
        cost4 = new javax.swing.JLabel();
        cost5 = new javax.swing.JLabel();
        cost6 = new javax.swing.JLabel();
        cost7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First name");

        jLabel2.setText("Last name");

        jLabel3.setText("Phone number");

        jLabel4.setText("Make");

        jLabel5.setText("Plate");

        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        jLabel8.setText("Model");

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("--");

        submit.setText("Submit");

        service1.setText("Hand wash");

        service2.setText("Integrated trolley dryer in the equipment");
        service2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service2ActionPerformed(evt);
            }
        });

        service3.setText("Special wash brushes");

        service4.setText("Special applications");
        service4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service4ActionPerformed(evt);
            }
        });

        service5.setText("orcelain coating and bodywork crystallization.");
        service5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service5ActionPerformed(evt);
            }
        });

        service6.setText("Deep washing");
        service6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service6ActionPerformed(evt);
            }
        });

        service7.setText("Delivery");

        home.setText("Home");

        cost1.setText("890000");

        cost2.setText("50000");

        cost3.setText("123000");

        cost4.setText("230000");

        cost5.setText("4500000");

        cost6.setText("356000");

        cost7.setText("100000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(plate, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(model, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(make, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(home)
                                .addGap(169, 169, 169)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cost2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cost1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service3)
                                .addGap(18, 18, 18)
                                .addComponent(cost3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service4)
                                .addGap(18, 18, 18)
                                .addComponent(cost4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cost5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service6)
                                .addGap(18, 18, 18)
                                .addComponent(cost6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(service7)
                                .addGap(18, 18, 18)
                                .addComponent(cost7))))
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(service1)
                    .addComponent(cost2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(plate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(service2)
                                    .addComponent(cost1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(service3)
                                    .addComponent(cost3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(service4)
                                    .addComponent(cost4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(service5)
                                    .addComponent(cost5))
                                .addGap(18, 18, 18)
                                .addComponent(service6))
                            .addComponent(cost6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(service7)
                            .addComponent(cost7))))
                .addGap(18, 18, 18)
                .addComponent(message)
                .addGap(18, 18, 18)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void service2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service2ActionPerformed

    private void service4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service4ActionPerformed

    private void service6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service6ActionPerformed

    private void service5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    
    public void addingButtons() {
        this.buttonGroup1.add(this.service1);
        this.buttonGroup1.add(this.service2);
        this.buttonGroup1.add(this.service3);
        this.buttonGroup1.add(this.service4);
        this.buttonGroup1.add(this.service5);
        this.buttonGroup1.add(this.service6);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel cost1;
    public javax.swing.JLabel cost2;
    public javax.swing.JLabel cost3;
    public javax.swing.JLabel cost4;
    public javax.swing.JLabel cost5;
    public javax.swing.JLabel cost6;
    public javax.swing.JLabel cost7;
    public javax.swing.JTextField firstName;
    public javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField lastName;
    public javax.swing.JTextField make;
    public javax.swing.JLabel message;
    public javax.swing.JTextField model;
    public javax.swing.JTextField phoneNumber;
    public javax.swing.JTextField plate;
    public javax.swing.JRadioButton service1;
    public javax.swing.JRadioButton service2;
    public javax.swing.JRadioButton service3;
    public javax.swing.JRadioButton service4;
    public javax.swing.JRadioButton service5;
    public javax.swing.JRadioButton service6;
    private javax.swing.JCheckBox service7;
    public javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
